resources:
- name: repo
  type: git
  check_every: 1hr
  source:
    uri: https://github.com/taylorsilva/carvel-images
    ignore_paths: [README.md]

# Images
- name: carvel-apps
  icon: docker
  type: registry-image
  source:
    repository: taylorsilva/carvel-apps
    tag: latest
    username: ((docker.username))
    password: ((docker.password))

- name: carvel-ytt
  icon: docker
  type: registry-image
  source:
    repository: taylorsilva/carvel-ytt
    username: ((docker.username))
    password: ((docker.password))

- name: carvel-kapp
  icon: docker
  type: registry-image
  source:
    repository: taylorsilva/carvel-kapp
    username: ((docker.username))
    password: ((docker.password))

- name: carvel-kbld
  icon: docker
  type: registry-image
  source:
    repository: taylorsilva/carvel-kbld
    username: ((docker.username))
    password: ((docker.password))

- name: carvel-kwt
  icon: docker
  type: registry-image
  source:
    repository: taylorsilva/carvel-kwt
    username: ((docker.username))
    password: ((docker.password))

- name: carvel-imgpkg
  icon: docker
  type: registry-image
  source:
    repository: taylorsilva/carvel-imgpkg
    username: ((docker.username))
    password: ((docker.password))

- name: carvel-vendir
  icon: docker
  type: registry-image
  source:
    repository: taylorsilva/carvel-vendir
    username: ((docker.username))
    password: ((docker.password))

# carvel apps
- name: ytt-release
  icon: github
  type: github-release
  source:
    owner: vmware-tanzu
    repository: carvel-ytt
    globs: ['*-linux-amd64']
    access_token: ((github_access_token))

- name: kapp-release
  icon: github
  type: github-release
  source:
    owner: vmware-tanzu
    repository: carvel-kapp
    globs: ['*-linux-amd64']
    access_token: ((github_access_token))

- name: kbld-release
  icon: github
  type: github-release
  source:
    owner: vmware-tanzu
    repository: carvel-kbld
    globs: ['*-linux-amd64']
    access_token: ((github_access_token))

- name: kwt-release
  icon: github
  type: github-release
  source:
    owner: vmware-tanzu
    repository: carvel-kwt
    globs: ['*-linux-amd64']
    access_token: ((github_access_token))

- name: imgpkg-release
  icon: github
  type: github-release
  source:
    owner: vmware-tanzu
    repository: carvel-imgpkg
    globs: ['*-linux-amd64']
    access_token: ((github_access_token))

- name: vendir-release
  icon: github
  type: github-release
  source:
    owner: vmware-tanzu
    repository: carvel-vendir
    globs: ['*-linux-amd64']
    access_token: ((github_access_token))

jobs:
- name: update-pipeline
  plan:
    - get: repo
      trigger: true
    - set_pipeline: carvel-apps
      file: repo/pipeline.yml

- name: all-apps
  plan:
    - in_parallel:
      - get: repo
        passed: [update-pipeline]
        trigger: true
      - get: ytt-release
        trigger: true
      - get: kapp-release
        trigger: true
      - get: kbld-release
        trigger: true
      - get: kwt-release
        trigger: true
      - get: imgpkg-release
        trigger: true
      - get: vendir-release
        trigger: true
    - task: build-carvel-apps-image
      file: repo/build-image.yml
      privileged: true
      params:
        DOCKERFILE: repo/Dockerfile-carvel-apps
    - put: carvel-apps
      params:
        image: image/image.tar

- name: ytt
  plan:
    - in_parallel:
      - get: repo
        passed: [update-pipeline]
        trigger: true
      - get: ytt-release
        trigger: true
    - task: build-carvel-ytt-image
      file: repo/build-image.yml
      privileged: true
      params:
        DOCKERFILE: repo/Dockerfile-ytt
    - load_var: version-tag
      file: ytt-release/version
    - put: carvel-ytt
      params:
        image: image/image.tar
        version: ((.:version-tag))
        bump_aliases: true

- name: kapp
  plan:
    - in_parallel:
      - get: repo
        passed: [update-pipeline]
        trigger: true
      - get: kapp-release
        trigger: true
    - task: build-carvel-kapp-image
      file: repo/build-image.yml
      privileged: true
      params:
        DOCKERFILE: repo/Dockerfile-kapp
    - load_var: version-tag
      file: kapp-release/version
    - put: carvel-kapp
      params:
        image: image/image.tar
        version: ((.:version-tag))
        bump_aliases: true

- name: kbld
  plan:
    - in_parallel:
      - get: repo
        passed: [update-pipeline]
        trigger: true
      - get: kbld-release
        trigger: true
    - task: build-carvel-kbld-image
      file: repo/build-image.yml
      privileged: true
      params:
        DOCKERFILE: repo/Dockerfile-kbld
    - load_var: version-tag
      file: kbld-release/version
    - put: carvel-kbld
      params:
        image: image/image.tar
        version: ((.:version-tag))
        bump_aliases: true

- name: kwt
  plan:
    - in_parallel:
      - get: repo
        passed: [update-pipeline]
        trigger: true
      - get: kwt-release
        trigger: true
    - task: build-carvel-kwt-image
      file: repo/build-image.yml
      privileged: true
      params:
        DOCKERFILE: repo/Dockerfile-kwt
    - load_var: version-tag
      file: kwt-release/version
    - put: carvel-kwt
      params:
        image: image/image.tar
        version: ((.:version-tag))
        bump_aliases: true

- name: imgpkg
  plan:
    - in_parallel:
      - get: repo
        passed: [update-pipeline]
        trigger: true
      - get: imgpkg-release
        trigger: true
    - task: build-carvel-imgpkg-image
      file: repo/build-image.yml
      privileged: true
      params:
        DOCKERFILE: repo/Dockerfile-imgpkg
    - load_var: version-tag
      file: imgpkg-release/version
    - put: carvel-imgpkg
      params:
        image: image/image.tar
        version: ((.:version-tag))
        bump_aliases: true

- name: vendir
  plan:
    - in_parallel:
      - get: repo
        passed: [update-pipeline]
        trigger: true
      - get: vendir-release
        trigger: true
    - task: build-carvel-vendir-image
      file: repo/build-image.yml
      privileged: true
      params:
        DOCKERFILE: repo/Dockerfile-vendir
    - load_var: version-tag
      file: vendir-release/version
    - put: carvel-vendir
      params:
        image: image/image.tar
        version: ((.:version-tag))
        bump_aliases: true
